### ISSUE TITLE
Add page: "Third Party Tools"

### ISSUE THREAD

**Issue by marisademeglio** [daisy/epubcheck-website#11]
List and short descriptions of interesting third party tools and apps based on EPUBCheck

**Comment by gregoriopellegrino** [comment]
This page is not in the nav :)

Could I add it myself?

**Comment by marisademeglio** [comment]
Sure, go ahead :) I'm not sure where this page should go, now that I think about it. What do you think?

If you want to experiment:

The main site nav is defined here:
https://github.com/daisy/epubcheck-website/blob/master/src/_includes/base.njk#L44

And the sidebar nav for the `user` and `dev` docs is defined here, for example:
https://github.com/daisy/epubcheck-website/blob/master/src/docs/user/user.json

You should be able to test it locally with `npm run serve` (`npm run build` will also work but then the postbuild process will throw some errors - which you can ignore).
