### ISSUE TITLE
Add a page "Getting help" for users?

### ISSUE THREAD

**Issue by gregoriopellegrino** [daisy/epubcheck-website#24]
I think it might be useful: some users who are not used to the command line might have problems and not know who to ask. We could suggest asking #eprdctn or opening an issue on GitHub.

**Comment by marisademeglio** [comment]
I agree, we should direct users to the right places to ask questions. Should this "getting help" page be an entry in the user guide?

**Comment by gregoriopellegrino** [comment]
Yes, I think so
