### ISSUE TITLE
Add page: "Getting started guide"

### ISSUE THREAD

**Issue by marisademeglio** [daisy/epubcheck-website#6]
step by step guided tutorial on how to run EPUBCheck

**Comment by gregoriopellegrino** [comment]
I can't figure out which page to write this information on, is it "Introduction" (`docs/user/index.md`)?

**Comment by marisademeglio** [comment]
Often I see the "quick start" page as the first entry after the introduction in end-user documentation. 

I just added a page for it, at `/docs/user/getting-started.md`. I figure we can move it later if we need to. 

What do you think? Does that sound ok?

**Comment by gregoriopellegrino** [comment]
Perfect, I'll work on it

**Comment by gregoriopellegrino** [comment]
TBD:

- [ ] add link to "Getting Help" (issue #24 )
