### ISSUE TITLE
Add page: "installation guide"

### ISSUE THREAD

**Issue by marisademeglio** [daisy/epubcheck-website#7]
Under subsection "CLI Documentation"

**Comment by gregoriopellegrino** [comment]
Question: is there really a need to install Java JDK on your mac or is Java JRE enough?

https://www.java.com/en/download/faq/techinfo.xml

**Comment by gregoriopellegrino** [comment]
> Question: is there really a need to install Java JDK on your mac or is Java JRE enough?

From EPUBcheck's README:

```
To run the tool you need a Java runtime (1.7 or above).
Any Operating System should do.
```

**Comment by marisademeglio** [comment]
Good question. The existing [CLI docs](https://daisy.github.io/epubcheck-website/docs/user/cli/#system-prerequisites) say JRE 1.6, but recommend 1.7 or 1.8 for image checks. And then in the explanation that follows, it says JDK 1.7/1.8, not JRE. So I'm not sure.
