### ISSUE TITLE
Add page: "usage guide (how to use the CLI for various scenarios)"

### ISSUE THREAD

**Issue by marisademeglio** [daisy/epubcheck-website#8]
Under subsection "CLI Documentation"

**Comment by gregoriopellegrino** [comment]
Do you know what the scenarios are? :)

**Comment by marisademeglio** [comment]
I don't know exactly what was meant by this but perhaps it's like "validating a packaged EPUB" or "validating a single file" or "validating an unzipped fileset" like what's described in the [CLI docs](https://daisy.github.io/epubcheck-website/docs/user/cli/#validating-a-packaged-epub)

**Comment by gregoriopellegrino** [comment]
I rearranged the examples that were there and added one.
